<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.2.3" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.0.1" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.0" />
    <PackageReference Include="Npgsql" Version="9.0.3" />
    <PackageReference Include="System.Collections" Version="4.3.0" />
    <PackageReference Include="System.Collections.Concurrent" Version="4.3.0" />
    <PackageReference Include="System.ServiceModel.Primitives" Version="8.1.1" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Avalonia\Utils\" />
    <Folder Include="MVVM\" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="dotnet-t4-project-tool" Version="2.3.1" />
  </ItemGroup>

  <ItemGroup>
    <TextTemplate Include="**/*.tt" />
  </ItemGroup>

  <Target Name="TransformT4" BeforeTargets="BeforeBuild">
    <Exec Command="t4 %(TextTemplate.Identity) -o %(TextTemplate.RelativeDir)%(TextTemplate.Filename).cs" />
  </Target>

</Project>
